import { PATH } from "./PATH";
export const MENU = {
  dashboard: [PATH.ADMIN_DASHBOARD],
  vendors: [PATH.ADMIN_VENDORS],
  admin_orders: [PATH.ADMIN_ORDERS],
  admin_settings: [PATH.ADMIN_CATEGORIES, PATH.ADMIN_PRODUCT_STATUSES, PATH.ADMIN_BANNERS, PATH.ADMIN_SPECIFICATIONS, PATH.ADMIN_SUBCATEGORIES],
  vendor_orders: [PATH.VENDOR_ORDERS, PATH.VENDOR_BULK_ORDERS, PATH.VENDOR_SHIPPING_ORDERS],
  pricing: [PATH.VENDOR_COUPONS, PATH.VENDOR_FLASH_SALES, PATH.VENDOR_BANNERS],
  vendor_customer_interaction: [PATH.VENDOR_REVIEWS, PATH.VENDOR_RATINGS, PATH.VENDOR_MESSAGING, PATH.VENDOR_RETURNS],
  vendor_store: [PATH.VENDOR_SETTINGS],
  
};